# Generated by Django 6.0.2 on 2026-05-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='student_class',
            field=models.CharField(default='10', max_length=10),
        ),
    ]
