# Generated by Django 6.0.5 on 2026-05-29 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(choices=[('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('JEE', 'JEE Aspirant'), ('NEET', 'NEET Aspirant')], default='11', max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('target_exam', models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET'), ('BOARD', 'Board Exams')], default='JEE', max_length=20)),
                ('study_streak', models.IntegerField(default=0)),
                ('total_questions_asked', models.IntegerField(default=0)),
                ('total_tests_taken', models.IntegerField(default=0)),
                ('total_study_hours', models.FloatField(default=0.0)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('avatar_color', models.CharField(default='#FF6B35', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
    ]
