# Generated by Django 6.0.2 on 2026-05-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_class',
            field=models.CharField(choices=[('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], default='10', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='target_exam',
            field=models.CharField(choices=[('BOARD', 'Board Exams')], default='BOARD', max_length=20),
        ),
    ]
