# Generated by Django 6.0.5 on 2026-05-29 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(default='JEE_MAIN', max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('chapter_name', models.CharField(max_length=200)),
                ('chapter_number', models.IntegerField(default=1)),
                ('weightage', models.FloatField(default=5.0)),
            ],
            options={
                'ordering': ['subject', 'chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('revised', 'Revised')], default='not_started', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.syllabuschapter')),
            ],
            options={
                'unique_together': {('user', 'chapter')},
            },
        ),
    ]
