# Generated by Django 6.0.2 on 2026-05-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabuschapter',
            name='detailed_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
