# Generated by Django 6.0.2 on 2026-05-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetest',
            name='class_level',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AlterField(
            model_name='practicetest',
            name='test_type',
            field=models.CharField(choices=[('JEE_MAIN', 'JEE Main'), ('JEE_ADV', 'JEE Advanced'), ('NEET', 'NEET'), ('BOARD', 'Board Exams'), ('CUSTOM', 'Custom')], default='JEE_MAIN', max_length=20),
        ),
    ]
